
version: '3'
    services: 
        app:
            build: 
                context: ./
                dockerfile: ./django-image/Dockerfile
            tty: true
            ports: 
                - 8000:8000
            working_dir: /app/myapp
            command: python manage.py runserver 0.0.0.0:8000
            volumes: 
                - ./app:/app
            depends_on:
                - db

        db:
            image: mysql:5.7
            environment: 
                MYSQL_ROOT_PASSWORD: Mayu0313
                MYSQL_USER: i16293
                MYSQL_PASSWORD: Mayu0313
            ports: 
                - 3306:3306
            volumes: 
                - ./db/data:/var/lib/mysql